/*
addressof operator (&):- gives the address of particular variable generated by the OS
                         same in C and C++

                        To fetch the address we have to use '%u' format specifier which is for unsigned integer

sizeof operator (sizeof(variable_name)) :- gives size of a variable in bytes
*/

#include<stdio.h>

int main()
{

    char cDiv = 'A';
    int iNum = 0;
    float fNum = 0.0;
    double dNum = 0.0;
    double *iPtr = &dNum;
    int iMarks[] = {11,21,51,101};

    printf("The address of cDiv is :- %u\n",&cDiv);
    printf("The address of iMarks is :- %u\n",iMarks); 
    //as the address of array is in array name so if we dont use the addressof operator (&) still it will give the address

    printf("The size of cDiv is :- %d\n",sizeof(cDiv));
    printf("The size of iMarks is :- %d\n",sizeof(iMarks));

    printf("Following are the sizeses of primitive data types in C & C++.\n");
    printf("The size of Character is :- %d\n",sizeof(cDiv)); // 1 byte
    printf("The size of Integer is :- %d\n",sizeof(iNum));  // 4 byte
    printf("The size of Float is :- %d\n",sizeof(fNum));    // 4 byte
    printf("The size of Double is :- %d\n",sizeof(dNum));   // 8 byte
    printf("The size of Pointer is :- %d, size of pointer is compiler dependent it may be 4/8 bytes.\n",sizeof(iPtr)); // 4 byte


    return 0;
}